examples/conv-opt/comparison/README.md
examples/conv-opt/comparison/tvm-conv2d.py

This is the first commit for tvm-conv2d benchmark code:
Modifications are made in the following two files:
- readme.md
- tvm-conv2d.py

[WIP] First commit for tvm-conv2d benchmark code

---

examples/DIPDialect/correlation2D.cpp

This PR intends to add the correct kernel for edge detection in DIP dialect's example.

Use correct kernel for edge detection via DIP dialect

---

docs/dip-opt.md

This PR intends to add basic documentation for 2D correlation in DIP dialect.

2D Correlation documentation

---

lib/Conversion/LowerDIP/LowerDIPPass.cpp

This PR intends to improve tail processing in DIP dialect by segregating it explicitly in right extrapolation part.

Improve tail processing in LowerDIPPass

---

examples/MLIRAffine/affine-max.mlir
examples/MLIRAffine/affine-parallel.mlir
examples/MLIRAffine/affine-store.mlir
examples/MLIRAffine/affine-vector.mlir
examples/MLIRAffine/makefile
examples/MLIRMemRef/makefile
examples/MLIRMemRef/memref-dim.mlir
examples/MLIRMemRef/memref-expand-shape.mlir
examples/MLIRMemRef/memref-rank.mlir
examples/MLIRMemRef/memref-reinterpret-cast.mlir
examples/MLIRTensor/makefile
examples/MLIRTensor/tensor-collapse-shape.mlir
examples/MLIRTensor/tensor-extract-slice.mlir
examples/MLIRTensor/tensor-extract.mlir
examples/MLIRTensor/tensor-from-elements.mlir
examples/MLIRTensor/tensor-insert-slice.mlir
examples/MLIRTensor/tensor-insert.mlir

add some affine examples and memref examples.

Add examples

---

examples/MLIRSCF/makefile
examples/MLIRSCF/scf-do-while.mlir
examples/MLIRSCF/scf-for.mlir
examples/MLIRSCF/scf-if.mlir
examples/MLIRTOSA/makefile
examples/MLIRTOSA/tosa-add.mlir
examples/MLIRTOSA/tosa-concat.mlir
examples/MLIRTOSA/tosa-log.mlir
examples/MLIRTOSA/tosa-sigmoid.mlir

Some examples for Tosa and SCF dialects

Tosa-Scf Examples

---

README.md
lib/Interface/core/Container.cpp

add check for `N` in memref::setStrides function.

Add check for set strides

---

docs/DomainSpecificSupport.md

linked discuss: https://github.com/buddy-compiler/buddy-mlir/pull/39#issuecomment-1146836983

add opencv build docs link (linux and windows)

---

examples/DIPDialect/CMakeLists.txt
examples/DIPDialect/dip.mlir
examples/DIPDialect/rotation2D.cpp
examples/README.md
include/Dialect/DIP/DIPOps.td
include/Interface/buddy/dip/dip.h
lib/Conversion/LowerDIP/LowerDIPPass.cpp

This PR intends to add support for 2D rotation in DIP dialect via dip.rotate_2d. Following tasks are to be strictly completed before its merger.
WIP Tasks :

Add support for dip.rotate_2d

---

docs/rvv-enviroment.md
thirdparty/build-rvv-env.sh

Adding a page explaining built process and minor improvements for the build script.

Setting up RVV enviroment

---

examples/ToyDSL/Toy.g4
examples/ToyDSL/function.toy
examples/ToyDSL/include/MLIRToyVisitor.h
examples/ToyDSL/makefile

Add function, add and mul, transpose.

Dsl function

---

examples/ToyDSL/Toy.g4
examples/ToyDSL/include/MLIRToyVisitor.h
examples/ToyDSL/makefile
examples/ToyDSL/struct.toy

Add struct

---

midend/lib/Utils/DIPUtils.cpp

[DIP] Added support for Irregular Kernels

---

midend/lib/Target/LLVMIR/Dialect/Gemmini/CMakeLists.txt
midend/lib/Target/LLVMIR/Dialect/RVV/CMakeLists.txt
tools/buddy-translate/CMakeLists.txt

This pr is only used to test the build process.

[Fix bug]fix build bug.

---

examples/MLIRSparseTensor/makefile
examples/MLIRSparseTensor/sparse-tensor-binary.mlir

[examplese][MLIRSparseTensor] Add initial example for binary operation

---

examples/ToyDSL/main.cpp

Fix toy DSL, now toy DSL can run.

[Toy DSL]fix toy DSL.

---

midend/lib/Conversion/LowerDAP/LowerDAPPass.cpp

**[Bug]**
The previous pass experienced a _double free_ error(when the input size is not multiple of ${SPLITING_SIZE}). 
This was the problem described in [issue #171](https://github.com/buddy-compiler/buddy-mlir/issues/171#issue-1787066024)

[DAP] Fix bug in @buddy_iir lowering pass

---

midend/include/Dialect/Gemmini/Gemmini.td
midend/include/Dialect/Gemmini/Transform.h
midend/lib/Conversion/LowerGemmini/LowerGemminiPass.cpp
midend/lib/Dialect/Gemmini/Transforms/LegalizeForLLVMExport.cpp

add gemmini hardware config `acc_rows` and `bank_rows`, fix `config_ld` bug.

[Gemmini Dialect]add gemmini hardware config.

---

midend/lib/Conversion/LowerGemmini/LowerGemminiPass.cpp

fix `lower-gemmini` pass opt parameter `addr_len`.

fix add_len.

---

frontend/Interfaces/buddy/DIP/ImageContainer.h
frontend/Interfaces/buddy/DIP/imgcodecs/bitstrm.h
frontend/Interfaces/buddy/DIP/imgcodecs/grfmt_png.h
frontend/Interfaces/buddy/DIP/imgcodecs/loadsave.h
frontend/Interfaces/buddy/DIP/imgcodecs/utils.h

This PR intends to help in the process of updating `buddy-benchmark` by marking related functions inline and applying other changes. This is done with the motive of resolving their definition reference in the single compilation unit created by linking multiple modular benchmarks in `buddy-benchmark`.

[DIP] Modify imgcodecs and ImageContainer to update buddy-benchmark

---

examples/BuddyWhisper/README.md

Update readme for whisper example

[Example] update readme

---

examples/BuddyMobileNetV3/CMakeLists.txt
examples/BuddyMobileNetV3/buddy-mobilenetv3-import.py
examples/BuddyMobileNetV3/buddy-mobilenetv3-main.cpp

- Remove the num_batches_tracked attribute.
- Removed the int64 type parameter file arg1.data

[BuddyMobileNetV3]Remove the num_batches_tracked attribute

---

examples/MLIRLinalg/linalg-conv2d_nhwc_fhwc.mlir

[Examples/MLIRLinalg] buddy-mlir/examples/MLIRLinalg/linalg-conv2d_nhwc_fhwc.mlir fix input argvs

[Examples/MLIRLinalg] linalg-conv2d_nhwc_fhwc.mlir fix input argvs

---

examples/DAPDialect/CMakeLists.txt
examples/DAPDialect/FIRVectorization.cpp
examples/README.md
frontend/Interfaces/buddy/DAP/DSP/FIR.h
midend/lib/Conversion/DAPVectorization/DAPVectorization.cpp

1. Add vectorized FIR lowering pattern (with tiling).
2. Update example 'README.md' file.
3. Add example for vectorized FIR lowering pattern.

[DAP] Add vectorized FIR lowering pattern (with tiling).

---

docs/AddPass.md

[docs] Add pass in  the midend doc.

---

midend/lib/Conversion/MatMulOptimization/BatchMatMulOptimize.cpp
tests/Conversion/batchmatmul-vectorization.mlir

Fixed multi-core computing capability of batchmatmul.
Previous changes resulted in the loss of multi-core capabilities, but this has now been fixed and it works normally with openmp to enable multi-core computing.

[midend/lib/Conversion/MatMulOptimization] Fixed multi-core computing capability of batchmatmul.
