examples/conv-opt/kernels.h
This PR intends to add header guard in file `kernels.h` which would help us compile programs where `kernels.h` is included multiple times.
=> Add header guard in kernels.h

README.md, examples/DIPDialect/corr2d.mlir, examples/DIPDialect/correlation2D.cpp, include/Dialect/DIP/DIPOps.h, include/Dialect/DIP/DIPOps.td, include/Interface/buddy/dip/dip.h, include/Interface/buddy/dip/memref.h, include/dip.hpp, lib/Conversion/LowerDIP/LowerDIPPass.cpp
DIP dialect specific functions/entities were defined/declared in a separate header file named `dip.hpp`. Proposed C++ interface for `dip.corr_2d` provides complete control over its functionalities to the user. A sample depicting its usage is : 
```
dip::Corr2D(input, kernel, output, centerX, centerY, boundary_option, constantValue(optional));
``` 
where 
```
input : Input image memref
kernel : Kernel memref
output : Output image memref
centerX : X co-ordinate of anchor point
centerY : Y co-ordinate of anchor point
boundary_option : Desired method of boundary extrapolation. 
Available options are dip::BOUNDARY_OPTION::CONSTANT_PADDING and dip::BOUNDARY_OPTION::REPLICATE_PADDING. 
constantValue : Optional argument which is expected to be provided with dip::BOUNDARY_OPTION::CONSTANT_PADDING. …
```
=> Improve DIP dialect interface

CMakeLists.txt
Currently, developers do not need ANTLR if they build it with examples disabled.
=> Search for ANTLR only if samples compilation enabled

README.md
Build LLVM submodule with "ninja check-mlir" instead of "ninja".
=> Remove a confusing instruction in README.md

.github/workflows/TestBuild.yml, tests/Actions/TestBuild.sh
* Saving build time by caching LLVM build results
* Enabling github actions for pull requests to check changes more often and give a developer faster feedback
* it takes a couple of minutes to run the pipeline if the llvvm build is cached
* Corresponding issue https://github.com/buddy-compiler/buddy-mlir/issues/19
* Update `TestBuild.yml` to use `actions/cache@v3` for caching
* llvm-project submodule revision is chosen as a cache key
* Update `TestBuild.sh` to set a build name for llvm-project and skip building llvm if the build directory already exists
* Examples
* Without caching ~ 1 hour 35 minutes: https://github.com/buddy-compiler/buddy-mlir/runs/7336914536?check_suite_focus=true 
* With caching
* 2m 56s https://github.com/buddy-compiler/buddy-mlir/runs/7338385660?check_suite_focus=tr …
=> Caching for LLVM build in github actions

examples/BudDialect/TestInlineInterface.mlir, examples/BudDialect/makefile, lib/Dialect/Bud/BudDialect.cpp
**Overview:**
An example for dialect interface.
**Detail:**
- Inline interface is a kind of dialect interfaces, which may be used in transformations & analyses(mlir-opt --inline).
- This PR intended to show how to create an inline interface(and what ever kinds of dialect interfaces), as well as how to use it(buddy-opt --inline). 
- Path: buddy-mlir/examples/BudDialect/TestInlineInterface.mlir.
- Use "make bud-inline-interface-run" to try it out.
=> An example for dialect interface: BudInlinerInterface

thirdparty/build-rvv-env.sh
LLVM D128465 introduced zstd as an optional compression method in LLVM. However with in the cross-compile environment there is no such library by default. This patch adds a cmake option that disable zstd support in build-rvv-env.sh.
Link: https://reviews.llvm.org/D128465
=> [thirdparty] disable LLVM zstd support rvv build scripts

include/Utils/DIPUtils.h, lib/Conversion/LowerDIP/LowerDIPPass.cpp, lib/Utils/DIPUtils.cpp
The `checkDIPCommonTypes` function uses C-style variadic arguments only for passing variadic numbers of the same type arguments, which should be avoided in C++. It is recommended to replace this usage with `std::initializer_list` or `std::vector`.
This PR also fixes the compilation failure in `clang++`, which will give a warning (as an error) for non-POD type `Value` in `va_arg`.
=> [DIP] replace C-style variadic function with std::vector

include/Utils/DIPUtils.h, include/Utils/Utils.h, lib/Conversion/ConvVectorization/CBConvVectorization.cpp, lib/Conversion/ConvVectorization/CMakeLists.txt, lib/Utils/DIPUtils.cpp, lib/Utils/Utils.cpp
This PR intends to improve `CBConvVectorization` lowering pass by adding support for neglecting null kernel elements. This should save us some extra assembly instructions (for FMA calculation, tail processing, etc.) in cases where we encounter a null kernel element. 
I am attaching benchmark results with and without this modification to illustrate the above behaviour. 
Before modification : 649 iterations
After modification : 1509 iterations
=> Improve CBConvVectorization Lowering pass

frontend/FrontendGen/include/AST.h, frontend/FrontendGen/include/CGModule.h, frontend/FrontendGen/lib/CGModule.cpp
This PR improves codes in `frontend/FrontendGen/lib/CGModule.cpp`.
A list of typos is below:
- `grammarNmae` -> `grammarName`
- `formuls` -> `formulas`
- `gramarName` -> `grammarName`
- `indexs` -> `indices`
- `opArgments` -> `opArguments`
- `resultsmap` -> `resultsMap`
- `argmentsMap` -> `argumentsMap`
- `buildrOp` -> `builderOp`
- `getbulderIdxs` -> `getBuilderIndices`
In lines `19` and `47`, `start` and `end` are used to store the result of `std::string::find`, which returns a `std::size_t`. The `std::string::npos` can never be stored in an `uint`, which causes the conditions (e.g. `start == std::string::npos`) below never satisfy.
In the original code, we have:
```cpp
llvm::SmallVector<llvm::StringRef> opArgments;
//...
os << "arg" << index << ";\n";
llvm::StringRef arg("arg" + …
```
=> Improve codes in CGModule

lib/Interface/core/Container.cpp
This PR intends to suppress the overflow warning by preventing an implicit conversion from "long unsigned int" to "int".
=> [Container] Fix implicit conversion between 'long unsigned' and 'int'

lib/Conversion/LowerDAP/LowerDAPPass.cpp, thirdparty/include/AudioFile.h
This PR removes the warnings generated due to DAP dialect and its dependent third party library.
Closes #92
=> [DAP] Removed warnings

examples/MLIRMath/makefile, examples/MLIRMath/math-rsqrt.mlir, examples/RVVDialect/.gitignore, examples/RVVDialect/makefile, examples/RVVDialect/rvv-rsqrt.mlir, include/Dialect/RVV/RVV.td, lib/Dialect/RVV/Transforms/LegalizeForLLVMExport.cpp
1. Add Rsqrt operation for RVV Dialect.
2. Add Resqrt lowering example from Math Dialect to X86vector Dialect for testing and reference.
When expressing deep learning models in MLIR ecosystem, **Rsqrt operation** (Reciprocal of the square-root) frequently shows up to participate in the calculations of BN or LN(Batch or Layer Normalization) in the form of `tosa.rsqrt` or `math.rsqrt`. In normal lowering pipeline, they will be divided into two operations, `llvm.intr.sqrt` and `llvm.fdiv`. It is neither efficient nor elegant.  
To address the problem, x86vector dialect supports [x86vector.avx.rsqrt](https://mlir.llvm.org/docs/Dialects/X86Vector/#x86vectoravxrsqrt-mlirx86vectorrsqrtop) to directly target [specific AVX instruction](https://uops.info/html-instr/VRSQRTPS_XMM_XMM.html), but …
=> [RVV] Add Rsqrt operation

include/Interface/buddy/core/ImageContainer.h, lib/Interface/core/ImageContainer.cpp, tests/Interface/core/ImageContainerTest.cpp
1. Add support for **NCHW layout** in ImageContainer. To customize the layout, an additional parameter `sizes[N]` (`N` is the rank of image data, normally 2 or 4), which represented the size of each dimentions, can be given like this:
```
cv::Mat image = imagePreprocessing();
Img<float, 4> input1(image);  // Represent NHWC layout by default.
intptr_t sizesInput2[4] = {1, image.rows, image.cols, 3};
Img<float, 4> input2(image, sizesInput2); // Represent NHWC layout.
intptr_t sizesInput3[4] = {1, 3, image.rows, image.cols};
Img<float, 4> input3(image, sizesInput3); // Represent NCHW layout.
```
2. Specify the error message.
~3. Replace `std::size_t` with `size_t` to improve readability.~
4. Support normalization when processing gray images with norm being set true.
5. Add ImageContainer …
=> [Container] Support more image channels layout in ImageContainer

examples/MLIRVector/vector-extract-strided-slice.mlir, examples/MLIRVector/vector-extract.mlir, examples/MLIRVector/vector-insert-strided-slice.mlir, examples/MLIRVector/vector-insert.mlir
improve examples for vector element access related operations in vector dialect, including:
- insert/extract
- insert-strided-slice/extract-strided-slice
This PR is a small and finished part of PR #90 .
=> [examples][MLIRVector] improve vector dialect examples for element access

README.md
By default we use the gnu linker to build llvm. lld is a linker from the llvm project and is much [faster](https://llvm.org/devmtg/2017-10/slides/Ueyama-lld.pdf) than the default gnu linker. This PR aims to give the user an option to use the lld linker while building llvm.
=> Add support for lld linker in build config of llvm

CMakeLists.txt, README.md, backend/llvm/lib/Target/RISCV/CMakeLists.txt, examples/lit.site.cfg.py.in, frontend/Interfaces/lib/CMakeLists.txt, midend/lib/Conversion/ConvVectorization/CMakeLists.txt, midend/lib/Conversion/LowerDIP/CMakeLists.txt, midend/lib/Utils/CMakeLists.txt, tests/lit.cfg.py, tests/lit.site.cfg.py.in
The PR is a solution for https://github.com/buddy-compiler/buddy-mlir/issues/132, I suppose a one-step building strategy by using LLVM_EXTERNAL_PROJECTS. 
It is implemented with reference to the build strategy of torch-mlir(https://github.com/llvm/torch-mlir/blob/0cf9ee340bc3264922e03b0df002e41c69184702/docs/development.md#building-torch-mlir-in-tree).
For one-step build, you can use the following commands:
```shell
$ cd buddy-mlir
$ git submodule update --init
$ cmake -G Ninja -Bbuild \
-DCMAKE_BUILD_TYPE=Release \
-DLLVM_ENABLE_PROJECTS="mlir;clang" \
-DLLVM_TARGETS_TO_BUILD="host;RISCV" \
-DLLVM_EXTERNAL_PROJECTS="buddy-mlir" \
-DLLVM_EXTERNAL_BUDDY_MLIR_SOURCE_DIR="$PWD" \
-DLLVM_ENABLE_ASSERTIONS=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
llvm/llvm
$ ninja check-mlir check-clang
$ ninja
$ …
```
=> [build strategy] Add a one-step building strategy by using LLVM_EXTERNAL_PROJECTS

thirdparty/include/AudioFile.h
This fixed the compile error on latest compiler toolchain.
=> [thirdparty] change std::int32_t to int32_t

.gitignore
The clangd lsp server will create a .cache directory in the buddy-mlir root directory which shouldn't be tracked by git.
=> [chore] add .cache directory into .gitignore

examples/DIPDialect/resize2D.cpp, frontend/Interfaces/buddy/DIP/DIP.h
This PR intends to make some changes in resize API to make it more consistent with OpenCV. Ref: https://github.com/buddy-compiler/buddy-benchmark/pull/61#issuecomment-1569535221
@taiqzheng, can you confirm if these changes would help your work?
=> [DIP] Make Resize API more consistent with OpenCV

examples/MLIRSparseTensor/makefile, examples/MLIRSparseTensor/sparse-tensor-fuse-tensor-cast.mlir
This commit add example shows the three possible effects of the rewrite pattern FuseTensorCast in PreSparsificationPass:
* Eliminate nop cast
* Fuse tensor.cast into producing operation
* Repair improper use of tensor.cast
=> [sparse_tensor] Add example for FuseTensorCast rewrite pattern

examples/MLIRSparseTensor/makefile, examples/MLIRSparseTensor/sparse-tensor-pack.mlir
This PR add example for operation `sparse_tensor.pack` and `sparse_tensor.unpack`.
=> [MLIRSparseTensor] Add sparse tensor pack example

examples/MLIRTOSA/makefile, examples/MLIRTOSA/tosa-resize.mlir
The PR aims to solve two bugs in TOSA examples
1) The pass pipeline bug
2) The bug in tosa.resizeOp
These bugs mostly occurred when we synced to the latest llvm
Solves #156
=> [Examples][TOSA] Bug in TOSA examples

CMakeLists.txt, midend/lib/CMakeLists.txt
In one-step build, llvm include directory will be prepended into include directories list, and this cause the IR backend using LLVM provided IntinsicImpl.inc file. This commit add `BEFORE` keyword into include_directories macro to force prepend buddy-mlir backend include directory.
Fixed #181
=> [cmake] fix one-step build

midend/include/Dialect/Gemmini/Transform.h, midend/lib/Conversion/LowerGemmini/LowerGemminiPass.cpp, midend/lib/Dialect/Gemmini/Transforms/LegalizeForLLVMExport.cpp
Reverts buddy-compiler/buddy-mlir#197
=> Revert "Fix gemmini legalize funcname."

examples/MLIRLinalg/linalg-batch-matmul.mlir, examples/MLIRLinalg/makefile, midend/lib/Conversion/MatMulOptimization/BatchMatMulOptimize.cpp, midend/lib/Conversion/MatMulOptimization/CMakeLists.txt, tools/buddy-opt/CMakeLists.txt, tools/buddy-opt/buddy-opt.cpp
Add "-batchmatmul-optimize" option in buddy-opt, the Matmul part is similar to [MatMulBroadcast.mlir](https://github.com/buddy-compiler/buddy-benchmark/blob/main/benchmarks/OpOptimization/MatMul/MatMulBroadcast.mlir) in buddy-benchmark. The batch-level loop utilizes affine.parallel. In the case of multiple batches, OpenMP can be utilized for multi-threaded acceleration. The A[batch_idx, 0, 0] which broadcasts in the Matmul will use `affine.prefetch` to prefetch in the outer loop. It could make the Op slightly faster. There's a bug, `if (A_elementType.isIntOrFloat())` cannot work properly. Even if the input type is floating-point, the integer branch will still execute. So I modified to `if (A_elementType.isIntOrFloat() && 0)` to skip the branch. So far the integer matrix is unavailable.
=> [midend][tests] Add broadcast BatchMatMul optimization pass and tests.

examples/ConvOpt/CMakeLists.txt
Now, when building the `libConv2D`, use the same path as in `frontend/Interfaces/lib/CMakeLists.txt` for building `libBuddyLibDAP` and `libBuddyLibDAP`. [Click here to view](https://github.com/buddy-compiler/buddy-mlir/blob/d43b4633666b2a66ee98e2cf8d34c0c76a2d0c0f/frontend/Interfaces/lib/CMakeLists.txt#L14C19-L14C19).
=> [examples][ConvOpt] Fixed libConv2D build error with wrong buddy-opt path.

CMakeLists.txt
The current one-step build strategy requires LLVM sources to be placed in the buddy-mlir project and named 'llvm'. This makes packaging a difficult task, as users can't build buddy-mlir with other working llvm source code that has a different version to the one provided by buddy-mlir.
This commit sets 'LLVM_PROJECT_SOURCE_DIR' to be the up dir of 'LLVM_MAIN_SRC_DIR'. 'LLVM_MAIN_SRC_DIR' is set when building within the llvm source directory, so it is safe to use it as the relative path to llvm project.
=> [cmake] fix llvm out-of-tree build for one-step build strategy

CMakeLists.txt
This can benefit downstream projects by allowing them to easily include headers from a distributed installation.
=> [frontend]: add install target for frontend headers

tests/Interface/core/CMakeLists.txt
I was getting an error saying that cmake was not able to find the target `buddy-image-container-test` when I was trying to have a stand-alone build of the `edge-detection` example for testing `conv-opt`. 
This patch should fix that problem and users should be able to build `edge-detection` target without building any DIP target first.
=> [examples] Fix stand-alone conv-opt edge detection build

.gitmodules
When I use the `git submodule update --init` command to clone a submodule, it is very slow! (Maybe I need a proxy!) However, I think we do not need the entire LLVM history or that of any other third-party submodule. Using shallow = true in the .gitmodules file for a submodule configuration will reduce data transfer: a shallow clone fetches only the most recent commits instead of the entire commit history of the repository, resulting in faster cloning operations.
=> [Git] Add shallow option to speed up pulling code

midend/lib/Conversion/LowerDAP/LowerDAPPass.cpp
-Fix Op
Fix buddy iir operation, use the same algorithm with the MLIR version in buddy-benchmark.
-Future work
Shoule add options for {splitting-size}, currently have 16 and 64. But only the splitting size is 8, buddy_biquad run faster than kfr_biquad(At 16 and 64, kfr run faster than mlir version, mlir version run faster than buddy version).
=> [DAP] Debug LowerDAPPass

examples/MLIRTOSA/makefile, examples/MLIRTOSA/tosa-concat.mlir
This PR intends to fix TOSA dialect examples by removing a no longer supported pass (`convert-linalg-to-llvm`) from the lowering pipelines. It also adds a simple target to get `linalg.generic` loops lowered from `tosa.resize`.
=> [Examples][TOSA] Improve Tosa Dialect examples

examples/BuddyLlama/README.md, requirements.txt
The BuddyLlama example requires `pybind11` package, which is not presented in `example/BuddyLlama/README.md`, so a supplement is made. ( #265 )
=> add steps for installing 'pybind11' in examples/BuddyLlama/README.md

.github/workflows/TestBuild.yml
This PR updates the cache and checkout action to version 4. There are no functional changes.
=> ci: bump cache & checkout version 4

examples/CMakeLists.txt, tests/CMakeLists.txt
When `ninja check-buddy` is called without any prior `ninja check-mlir`, the following test failure is raised:
```
<...>/linalg-transpose-f32.mlir.script: line 1: <...>/buddy-mlir/build/./bin/mlir-cpu-runner: No such file or director
```
This PR fixes this by explicitly setting `mlir-cpu-runner` as a dependency of buddy tests and examples.
=> [NFC] Make buddy tests and examples depends on `mlir-cpu-runner`

frontend/Interfaces/lib/CMakeLists.txt
Ninja introduced different build graph algorithm in version v1.12.0, which will required project to explicitly specify dependencies. Without this commit, ninja v1.12.0 will not link mlir-translate and llc before the DAP target and causing build failure.
=> frontend: add missing dependencies into DAP target

frontend/Interfaces/buddy/DAP/AudioContainer.h, tests/Interface/core/AudioContainerTest.cpp
**Deviation:**
There might be slight discrepancies in the sample values after encoding, with a difference of one when represented as bytes (uint8_t).
**Example:**
Raw audio data:  fff7 
Encoded result: fff8
=> [Audio Container] Add encoder for wav audio format.

frontend/Interfaces/buddy/DAP/DSP/WhisperPreprocess.h, frontend/Interfaces/lib/DAP-extend.mlir, midend/include/Dialect/DAP/DAPOps.td, midend/lib/Conversion/ExtendDAP/ExtendDAPPass.cpp
> Change the format of **`dap.whisper_preprocess`** and top level function **`@buddy_whisperPreprocess`**
> Previous version: 
>  ```mlir
>  dap.whisper_preprocess %input, %output : memref<?xf64>, memref<1x80x3000xf32>
>  ```
> Current version:
>  ```mlir
>  %output = dap.whisper_preprocess %input : memref<?xf64> to memref<1x80x3000xf32>
>  ```
>
>For changing **`%output`** from operand to result, we can use **`replaceOp()`** to replace the combination of **`memref.copy`** and **`eraseOp()`**.
=> [DAP/Whisper] Extract RFFT operation from 'dap.whisper_preprocess'.

frontend/Interfaces/buddy/DIP/ImageContainer.h, tests/Interface/core/ImageContainerTest.cpp
Draft PR for opencv test integration #115
=> opencv test draft for ImageContainer

examples/DAPDialect/FIRLowpass.cpp, frontend/Interfaces/buddy/DAP/DSP/FIR.h, frontend/Interfaces/lib/CMakeLists.txt, midend/lib/Conversion/LowerDAP/LowerDAPPass.cpp
1. Redesign the `dap.fir` implementation.
The previous design used `linalg.conv1D` for FIR operation, noting two differences: 
- FIR operation include zero paddings before the actual input.
- FIR operation do not incorporate bias in the formula.
2. Reformat the `frontend/Interfaces/lib/CMakeLists.txt` file.
=> [DAP] Debug 'dap.fir' operation.

examples/DIPDialect/resize4D_nchw.cpp, frontend/Interfaces/buddy/DIP/ImgContainer.h
=> [DIP] add bmp encode to write image

midend/lib/Conversion/MatMulOptimization/MatMulTransposeBVec.cpp, tests/Conversion/matmul-transpose-b-vectorization.mlir
Current vectorization pass of matmul-transpose-b reduce the vector in each iteration and accumulate it to the result element. This commit modify it into elementwise addition and do the reduction after the inner loop with reassoc enabled.
This leads to a ~4x speedup on musepi
```
----------------------------------------------------------------------------------
Benchmark                                        Time             CPU   Iterations
----------------------------------------------------------------------------------
benchMatmulTransposeB/matmul                   334 ms          334 ms            2
benchMatmulTransposeB/matmul_vectorized        707 ms          707 ms            1
benchMatmulTransposeB/matmul_opt0              174 ms          174 ms            4 …
```
=> [midend] Optimization on matmul-transpose-b vectorization

midend/lib/Utils/Utils.cpp
The `insertZeroConstantOp` utility is used in matmul vectorization passes, but it currently only supports `f32` and `f64`. This PR adds support for other float types.
=> [midend] Support arbitrary float type of zero constants

examples/BuddyDeepSeekR1/CMakeLists.txt
- Move convert-vector-to-scf before convert-scf-to-openmp to preserve parallelization opportunities
- Remove duplicate convert-arith-to-llvm calls
- Unify compilation pipeline structure
=> fix: Correct MLIR pass execution order and remove redundant conversions
